[package]
name = "wsk"
version = "0.1.0"
edition = "2024"

[dependencies]
approx = "0.5.1"
ndarray = { version = "0.16.1", default-features = false, features = ["approx", "serde"] }
serde = "1.0"
tracing = "0.1.41"

[dev-dependencies]
csv = "1.3"
tracing-subscriber = "0.3.19"
