[package]
name = "wsk"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = { version = "0.16.1", default-features = false, features = ["approx", "serde"] }
serde = "1.0"

[dev-dependencies]
csv = "1.3"
